version: '3'

services:

  httpUnderConst:
    container_name: httpUnderConst
    restart: always
    image: nginx:alpine
    ports:
      - "7000:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
